export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  DASHBOARD_PROFILE: '/dashboard/profile',
  INTERVIEW_SETUP: '/interview-setup',
  INTERVIEW_ROOM: '/interview-room',
  BEHAVIORAL_ROOM: '/behavioral-room',
  DSA_ROOM: '/dsa-room',
  DSA_ROOM_SOLO: '/dsa-room-solo',
  NSD_ROOM: '/nsd-room',
  SCORING: '/scoring',
  PRACTICE_PROBLEMS: '/practice-problems',
  QUESTION_BANK: '/question-bank',
  QUESTION_BANK_DETAIL: '/question-bank/:probeId',
  ADMIN: '/admin',
  ADMIN_TESTCASES: '/admin/testcases',
  ADMIN_NSD_PROBLEMS: '/admin/nsd-problems',
  ADMIN_QUESTION_BANK: '/admin/question-bank',
  ADMIN_USERS: '/admin/users',
  ADMIN_ANALYTICS: '/admin/analytics',
  BUY_CREDITS: '/buy-credits',
  PAYMENT_RESULT: '/payment/result',
  WALLET_HISTORY: '/wallet/history',
}
