export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  DASHBOARD_PROFILE: '/dashboard/profile',
  INTERVIEW_SETUP: '/interview-setup',
  INTERVIEW_ROOM: '/interview-room',
  BEHAVIORAL_ROOM: '/behavioral-room',
  COMBAT_ROOM: '/combat-room',
  DSA_ROOM: '/dsa-room',
  DSA_ROOM_SOLO: '/dsa-room-solo',
  SD_ROOM: '/sd-room',
  SCORING: '/scoring',
  PRACTICE_PROBLEMS: '/practice-problems',
  ADMIN: '/admin',
  ADMIN_TESTCASES: '/admin/testcases',
  ADMIN_SD_PROBLEMS: '/admin/sd-problems',
  ADMIN_QUESTION_BANK: '/admin/question-bank',
}
