export const QUESTION_PROBE_STAGES = [
  'stage_1_culture_fit',
  'stage_2_tech_stack',
  'stage_3_domain_knowledge',
  'stage_4_cv_deep_dive',
  'stage_5_soft_skills',
] as const;

export const QUESTION_PROBE_ROLE_FAMILIES = [
  'backend',
  'frontend',
  'fullstack',
  'devops',
  'data',
  'qa',
  'security',
] as const;

export const QUESTION_PROBE_LEVELS = ['junior', 'mid', 'senior'] as const;

export const QUESTION_PROBE_TYPES = [
  'behavioral',
  'technical_depth',
  'trade_off',
  'debugging',
  'cv_claim_verification',
  'situational',
] as const;

export const QUESTION_PROBE_COMPETENCIES = [
  'ownership', // Chịu trách nhiệm về kết quả công việc, có khả năng dẫn dắt và chịu trách nhiệm về các quyết định quan trọng.
  'conflict_handling', // Khả năng xử lý xung đột, giải quyết mâu thuẫn trong nhóm hoặc với các bên liên quan.
  'learning_agility', // Khả năng học hỏi nhanh chóng, thích nghi với các tình huống mới và áp dụng kiến thức vào thực tế.
  'technical_fundamentals', // Kiến thức cơ bản về kỹ thuật, hiểu biết về các nguyên tắc và công nghệ cơ bản trong lĩnh vực của mình.
  'trade_off_analysis', // Khả năng phân tích và đưa ra quyết định dựa trên việc cân nhắc các lựa chọn khác nhau, hiểu rõ các ưu nhược điểm của từng phương án.
  'system_thinking', // Khả năng nhìn nhận vấn đề một cách tổng thể, hiểu mối quan hệ giữa các thành phần trong hệ thống và tác động của chúng đến nhau.
  'problem_solving', // Khả năng giải quyết vấn đề một cách hiệu quả, tìm ra nguyên nhân gốc rễ và đưa ra các giải pháp khả thi.
  'communication', // Khả năng giao tiếp hiệu quả, truyền đạt ý tưởng một cách rõ ràng và lắng nghe phản hồi từ người khác.
  'collaboration', // Khả năng làm việc nhóm, chia sẻ kiến thức và hỗ trợ lẫn nhau trong quá trình thực hiện công việc.
  'impact_measurement', // Khả năng xác định và đo lường tác động của các hoạt động hoặc quyết định đối với kết quả mong muốn.
  'leadership', // Khả năng dẫn dắt, mentor và phát triển người khác; ảnh hưởng kỹ thuật vượt ra ngoài phạm vi cá nhân.
] as const;

export const QUESTION_PROBE_LANGUAGES = ['vi', 'en', 'ja'] as const;

export const QUESTION_PROBE_STATUSES = [
  'draft',
  'in_review',
  'active',
  'retired',
  'needs_revision',
] as const;

export const QUESTION_PROBE_FOLLOW_UP_TRIGGERS = [
  'missing_metric',
  'missing_context',
  'missing_tradeoff',
  'vague_answer',
  'missing_personal_contribution',
  'missing_consequence',
  'missing_reflection',
] as const;

export const QUESTION_PROBE_TOPIC_TAGS = [
  // Canonical interview topics. Low-level details should live in expectedSignals.
  'closure',
  'scope',
  'hoisting_tdz',
  'this_binding',
  'prototype_chain',
  'type_coercion',
  'immutability',
  'array_iteration',
  'event_loop',
  'async_programming',
  'event_delegation',
  'module_system',
  'accessibility',
  'browser_performance',
  'state_management',
  'dependency_management',
  'filesystem_io',
  'binary_data',
  'type_system',
  'type_inference',
  'union_types',
  'type_narrowing',
  'discriminated_union',
  'structural_typing',
  'generics',
  'utility_types',
  'type_operators',
  'null_safety',
  'any_unknown_never',
  'type_assertion',
  'http_semantics',
  'http_methods',
  'status_codes',
  'routing',
  'api_contract',
  'api_design',
  'request_validation',
  'error_handling',
  'debugging',
  'testing_strategy',
  'contract_testing',
  'performance_optimization',
  'pagination',
  'content_negotiation',
  'api_versioning',
  'cors',
  'rate_limiting',
  'idempotency',
  'authentication',
  'authorization',
  'jwt_lifecycle',
  'token_storage',
  'refresh_token',
  'session_management',
  'csrf',
  'xss',
  'sql_injection',
  'password_hashing',
  'application_security',
  'audit_logging',
  'threat_modeling',
  'relational_model',
  'schema_design',
  'constraints',
  'joins',
  'aggregation',
  'indexing',
  'query_planning',
  'normalization',
  'denormalization',
  'transactions',
  'acid',
  'isolation_levels',
  'locking',
  'migration',
  'n_plus_1',
  'data_integrity',
  'data_quality',
  'data_partitioning',
  'data_lineage',
  'oop',
  'encapsulation',
  'abstraction',
  'inheritance',
  'polymorphism',
  'composition',
  'interface_design',
  'solid',
  'dependency_inversion',
  'cohesion_coupling',
  'repository_pattern',
  'dependency_injection',
  'module_architecture',
  'provider_lifecycle',
  'request_lifecycle',
  'guards_pipes_interceptors',
  'middleware_pipeline',
  'exception_handling',
  'circular_dependency',
  'configuration',
  'caching',
  'batching',
  'concurrency',
  'backpressure',
  'timeouts_retries',
  'observability',
  'graceful_shutdown',
  'containerization',
  'dockerfile',
  'image_layers',
  'volumes',
  'container_networking',
  'compose',
  'environment_config',
  'secrets_management',
  'healthchecks',
  'ci_cd',
  'deployment',
  'cloud_architecture',
  'cloud_security',
  'cloud_networking',
  'serverless_architecture',
  'infrastructure_as_code',
  'scalability',
  'cost_optimization',
  'incident_response',
  'event_driven_architecture',
  'microservices_architecture',
  'messaging',
  'eventual_consistency',
  'outbox_pattern',
] as const;

export type QuestionProbeStage = (typeof QUESTION_PROBE_STAGES)[number];
export type QuestionProbeRoleFamily =
  (typeof QUESTION_PROBE_ROLE_FAMILIES)[number];
export type QuestionProbeLevel = (typeof QUESTION_PROBE_LEVELS)[number];
export type QuestionProbeType = (typeof QUESTION_PROBE_TYPES)[number];
export type QuestionProbeCompetency =
  (typeof QUESTION_PROBE_COMPETENCIES)[number];
export type QuestionProbeLanguage = (typeof QUESTION_PROBE_LANGUAGES)[number];
export type QuestionProbeStatus = (typeof QUESTION_PROBE_STATUSES)[number];
export type QuestionProbeFollowUpTrigger =
  (typeof QUESTION_PROBE_FOLLOW_UP_TRIGGERS)[number];
export type QuestionProbeTopicTag = (typeof QUESTION_PROBE_TOPIC_TAGS)[number];

export interface TaxonomyOption {
  key: string;
  label: string;
  description?: string;
  group?: string;
}

export interface TechTagGroup {
  group: string;
  tags: string[];
}

export interface TopicTagGroup {
  group: string;
  tags: QuestionProbeTopicTag[];
}

export interface QuestionBankTaxonomy {
  stages: TaxonomyOption[];
  roleFamilies: TaxonomyOption[];
  levels: TaxonomyOption[];
  types: TaxonomyOption[];
  competencies: TaxonomyOption[];
  languages: TaxonomyOption[];
  statuses: TaxonomyOption[];
  followUpTriggers: TaxonomyOption[];
  techTagGroups: TechTagGroup[];
  topicTagGroups: TopicTagGroup[];
}

export const QUESTION_PROBE_TECH_TOPIC_BASELINES: Partial<
  Record<string, QuestionProbeTopicTag[]>
> = {
  javascript: [
    'closure',
    'scope',
    'hoisting_tdz',
    'this_binding',
    'prototype_chain',
    'type_coercion',
    'event_loop',
    'async_programming',
    'immutability',
  ],
  react: [
    'composition',
    'state_management',
    'event_delegation',
    'browser_performance',
    'accessibility',
  ],
  redux: ['state_management', 'immutability', 'debugging'],
  nextjs: [
    'routing',
    'module_system',
    'deployment',
    'serverless_architecture',
    'performance_optimization',
  ],
  vite: ['module_system', 'dependency_management', 'browser_performance'],
  typescript: [
    'type_system',
    'type_inference',
    'union_types',
    'type_narrowing',
    'structural_typing',
    'generics',
    'null_safety',
    'any_unknown_never',
  ],
  rest: [
    'http_semantics',
    'http_methods',
    'status_codes',
    'api_contract',
    'api_design',
    'request_validation',
    'error_handling',
    'idempotency',
    'pagination',
  ],
  express: [
    'middleware_pipeline',
    'routing',
    'request_lifecycle',
    'error_handling',
    'request_validation',
  ],
  nodejs: [
    'event_loop',
    'async_programming',
    'module_system',
    'dependency_management',
    'concurrency',
    'backpressure',
    'graceful_shutdown',
  ],
  fastify: [
    'middleware_pipeline',
    'routing',
    'request_lifecycle',
    'error_handling',
    'request_validation',
  ],
  graphql: ['api_contract', 'api_design', 'n_plus_1', 'batching'],
  grpc: ['api_contract', 'messaging', 'timeouts_retries', 'error_handling'],
  websocket: [
    'messaging',
    'event_driven_architecture',
    'concurrency',
    'backpressure',
  ],
  nestjs: [
    'dependency_injection',
    'module_architecture',
    'provider_lifecycle',
    'request_lifecycle',
    'guards_pipes_interceptors',
    'exception_handling',
    'configuration',
  ],
  jwt: [
    'authentication',
    'authorization',
    'jwt_lifecycle',
    'token_storage',
    'refresh_token',
    'session_management',
  ],
  postgresql: [
    'relational_model',
    'schema_design',
    'joins',
    'indexing',
    'query_planning',
    'transactions',
    'acid',
    'isolation_levels',
    'n_plus_1',
  ],
  sql: [
    'relational_model',
    'schema_design',
    'constraints',
    'joins',
    'aggregation',
    'indexing',
    'query_planning',
    'transactions',
    'data_integrity',
    'sql_injection',
  ],
  mysql: [
    'relational_model',
    'schema_design',
    'joins',
    'indexing',
    'query_planning',
    'transactions',
    'acid',
    'isolation_levels',
  ],
  mongodb: [
    'schema_design',
    'indexing',
    'aggregation',
    'denormalization',
    'data_integrity',
  ],
  typeorm: [
    'repository_pattern',
    'schema_design',
    'query_planning',
    'transactions',
    'n_plus_1',
  ],
  docker: [
    'containerization',
    'dockerfile',
    'image_layers',
    'volumes',
    'container_networking',
    'compose',
    'environment_config',
    'healthchecks',
  ],
  redis: ['caching', 'idempotency', 'timeouts_retries', 'observability'],
  bullmq: [
    'messaging',
    'event_driven_architecture',
    'idempotency',
    'timeouts_retries',
  ],
  kafka: [
    'event_driven_architecture',
    'messaging',
    'eventual_consistency',
    'idempotency',
    'outbox_pattern',
  ],
  rabbitmq: [
    'event_driven_architecture',
    'messaging',
    'eventual_consistency',
    'idempotency',
  ],
  rxjs: ['async_programming', 'event_driven_architecture', 'backpressure'],
  class_validator: ['request_validation'],
  class_transformer: ['request_validation', 'type_system'],
  zod: ['request_validation', 'api_contract'],
  joi: ['request_validation', 'api_contract'],
  express_validator: ['request_validation'],
  openapi: ['api_contract', 'api_design'],
  swagger: ['api_contract', 'api_design'],
  v8: ['event_loop', 'performance_optimization'],
  npm: ['dependency_management', 'module_system', 'ci_cd'],
  aws: [
    'cloud_architecture',
    'cloud_security',
    'cloud_networking',
    'deployment',
    'observability',
    'cost_optimization',
    'scalability',
  ],
  ec2: ['deployment', 'cloud_networking', 'scalability'],
  s3: ['data_integrity', 'cloud_architecture'],
  rds: ['relational_model', 'data_integrity', 'cloud_architecture'],
  dynamodb: ['schema_design', 'data_integrity', 'scalability'],
  lambda: ['serverless_architecture', 'deployment', 'timeouts_retries'],
  ecs: ['containerization', 'deployment', 'scalability'],
  iam: ['authorization', 'cloud_security'],
  vpc: ['cloud_networking', 'cloud_security'],
  eventbridge: ['event_driven_architecture', 'messaging'],
  cloudformation: ['infrastructure_as_code', 'deployment'],
  cloudwatch: ['observability'],
  cloudtrail: ['observability', 'cloud_security'],
  secrets_manager: ['secrets_management', 'cloud_security'],
  kms: ['secrets_management', 'cloud_security'],
  step_functions: ['event_driven_architecture', 'timeouts_retries'],
  autoscaling: ['scalability', 'deployment'],
  serverless: ['serverless_architecture', 'deployment'],
  sqs: ['messaging', 'timeouts_retries'],
  pubsub: ['messaging', 'event_driven_architecture'],
  kubernetes: ['containerization', 'deployment', 'healthchecks', 'scalability'],
  terraform: ['infrastructure_as_code', 'deployment'],
  github_actions: ['ci_cd', 'deployment', 'testing_strategy'],
  prometheus: ['observability'],
  grafana: ['observability'],
  opentelemetry: ['observability'],
  jest: ['testing_strategy', 'debugging'],
  vitest: ['testing_strategy', 'debugging'],
  playwright: ['testing_strategy', 'debugging', 'browser_performance'],
  cypress: ['testing_strategy', 'debugging', 'browser_performance'],
  selenium: ['testing_strategy', 'debugging', 'browser_performance'],
  postman: ['api_contract', 'testing_strategy', 'request_validation'],
  airflow: ['data_quality', 'data_lineage', 'observability'],
  bigquery: ['query_planning', 'data_partitioning', 'data_quality'],
  dbt: ['data_quality', 'data_lineage', 'dependency_management'],
  spark: ['data_partitioning', 'performance_optimization'],
  snowflake: ['query_planning', 'data_partitioning', 'data_quality'],
};

export const QUESTION_BANK_TAXONOMY: QuestionBankTaxonomy = {
  stages: [
    { key: 'stage_1_culture_fit', label: 'Culture Fit' },
    { key: 'stage_2_tech_stack', label: 'Tech Stack Deep-Dive' },
    { key: 'stage_3_domain_knowledge', label: 'Domain Knowledge' },
    { key: 'stage_4_cv_deep_dive', label: 'CV Deep-Dive' },
    { key: 'stage_5_soft_skills', label: 'Soft Skills' },
  ],
  roleFamilies: [
    { key: 'backend', label: 'Backend' },
    { key: 'frontend', label: 'Frontend' },
    { key: 'fullstack', label: 'Fullstack' },
    { key: 'devops', label: 'DevOps/SRE' },
    { key: 'data', label: 'Data' },
    { key: 'qa', label: 'QA' },
    { key: 'security', label: 'Security' },
  ],
  levels: [
    { key: 'junior', label: 'Junior' },
    { key: 'mid', label: 'Mid-level' },
    { key: 'senior', label: 'Senior' },
  ],
  types: [
    { key: 'behavioral', label: 'Behavioral' },
    { key: 'technical_depth', label: 'Technical Depth' },
    { key: 'trade_off', label: 'Trade-off' },
    { key: 'debugging', label: 'Debugging' },
    { key: 'cv_claim_verification', label: 'CV Claim Verification' },
    { key: 'situational', label: 'Situational' },
  ],
  competencies: [
    { key: 'ownership', label: 'Ownership' },
    { key: 'conflict_handling', label: 'Conflict Handling' },
    { key: 'learning_agility', label: 'Learning Agility' },
    { key: 'technical_fundamentals', label: 'Technical Fundamentals' },
    { key: 'trade_off_analysis', label: 'Trade-off Analysis' },
    { key: 'system_thinking', label: 'System Thinking' },
    { key: 'problem_solving', label: 'Problem Solving' },
    { key: 'communication', label: 'Communication' },
    { key: 'collaboration', label: 'Collaboration' },
    { key: 'impact_measurement', label: 'Impact Measurement' },
    { key: 'leadership', label: 'Leadership & Mentorship' },
  ],
  languages: [
    { key: 'vi', label: 'Vietnamese' },
    { key: 'en', label: 'English' },
    { key: 'ja', label: 'Japanese' },
  ],
  statuses: [
    { key: 'draft', label: 'Draft' },
    { key: 'in_review', label: 'In Review' },
    { key: 'active', label: 'Active' },
    { key: 'retired', label: 'Retired' },
    { key: 'needs_revision', label: 'Needs Revision' },
  ],
  followUpTriggers: [
    { key: 'missing_metric', label: 'Missing metric' },
    { key: 'missing_context', label: 'Missing context' },
    { key: 'missing_tradeoff', label: 'Missing trade-off' },
    { key: 'vague_answer', label: 'Vague answer' },
    {
      key: 'missing_personal_contribution',
      label: 'Missing personal contribution',
    },
    { key: 'missing_consequence', label: 'Missing consequence' },
    { key: 'missing_reflection', label: 'Missing reflection' },
  ],
  techTagGroups: [
    {
      group: 'frontend',
      tags: [
        'react',
        'vue',
        'angular',
        'nextjs',
        'javascript',
        'typescript',
        'redux',
        'tailwind',
        'vite',
      ],
    },
    {
      group: 'backend',
      tags: [
        'nodejs',
        'nestjs',
        'express',
        'fastify',
        'java',
        'spring_boot',
        'dotnet',
        'go',
        'python',
        'django',
        'fastapi',
        'rest',
        'graphql',
        'grpc',
        'websocket',
        'rxjs',
        'class_validator',
        'class_transformer',
        'zod',
        'joi',
        'express_validator',
        'openapi',
        'swagger',
      ],
    },
    {
      group: 'database_storage',
      tags: [
        'postgresql',
        'sql',
        'mysql',
        'mongodb',
        'typeorm',
        'redis',
        'elasticsearch',
      ],
    },
    {
      group: 'messaging_async',
      tags: ['kafka', 'rabbitmq', 'bullmq', 'sqs', 'pubsub'],
    },
    {
      group: 'runtime_tooling',
      tags: ['v8', 'npm'],
    },
    {
      group: 'devops_sre',
      tags: [
        'docker',
        'kubernetes',
        'terraform',
        'github_actions',
        'prometheus',
        'grafana',
        'opentelemetry',
      ],
    },
    {
      group: 'cloud',
      tags: [
        'aws',
        'gcp',
        'azure',
        'ec2',
        's3',
        'rds',
        'dynamodb',
        'lambda',
        'ecs',
        'eks',
        'iam',
        'vpc',
        'eventbridge',
        'cloudformation',
        'cloudwatch',
        'cloudtrail',
        'secrets_manager',
        'kms',
        'step_functions',
        'autoscaling',
        'serverless',
      ],
    },
    {
      group: 'data_ai',
      tags: [
        'airflow',
        'spark',
        'dbt',
        'bigquery',
        'snowflake',
        'pytorch',
        'tensorflow',
      ],
    },
    {
      group: 'qa_security',
      tags: [
        'jest',
        'vitest',
        'playwright',
        'cypress',
        'selenium',
        'postman',
        'oauth2',
        'jwt',
      ],
    },
  ],
  topicTagGroups: [
    {
      group: 'javascript_runtime',
      tags: [
        'closure',
        'scope',
        'hoisting_tdz',
        'this_binding',
        'prototype_chain',
        'type_coercion',
        'immutability',
        'array_iteration',
        'event_loop',
        'async_programming',
        'event_delegation',
        'module_system',
        'dependency_management',
        'filesystem_io',
        'binary_data',
      ],
    },
    {
      group: 'frontend_browser',
      tags: ['accessibility', 'browser_performance', 'state_management'],
    },
    {
      group: 'typescript_type_system',
      tags: [
        'type_system',
        'type_inference',
        'union_types',
        'type_narrowing',
        'discriminated_union',
        'structural_typing',
        'generics',
        'utility_types',
        'type_operators',
        'null_safety',
        'any_unknown_never',
        'type_assertion',
      ],
    },
    {
      group: 'http_api',
      tags: [
        'http_semantics',
        'http_methods',
        'status_codes',
        'routing',
        'api_contract',
        'api_design',
        'request_validation',
        'error_handling',
        'debugging',
        'testing_strategy',
        'contract_testing',
        'performance_optimization',
        'pagination',
        'content_negotiation',
        'api_versioning',
        'cors',
        'rate_limiting',
        'idempotency',
      ],
    },
    {
      group: 'auth_security',
      tags: [
        'authentication',
        'authorization',
        'jwt_lifecycle',
        'token_storage',
        'refresh_token',
        'session_management',
        'csrf',
        'xss',
        'sql_injection',
        'password_hashing',
        'application_security',
        'audit_logging',
        'threat_modeling',
      ],
    },
    {
      group: 'database_sql',
      tags: [
        'relational_model',
        'schema_design',
        'constraints',
        'joins',
        'aggregation',
        'indexing',
        'query_planning',
        'normalization',
        'denormalization',
        'transactions',
        'acid',
        'isolation_levels',
        'locking',
        'migration',
        'n_plus_1',
        'data_integrity',
        'data_quality',
        'data_partitioning',
        'data_lineage',
      ],
    },
    {
      group: 'oop_design',
      tags: [
        'oop',
        'encapsulation',
        'abstraction',
        'inheritance',
        'polymorphism',
        'composition',
        'interface_design',
      ],
    },
    {
      group: 'solid_design',
      tags: [
        'solid',
        'dependency_inversion',
        'cohesion_coupling',
        'repository_pattern',
      ],
    },
    {
      group: 'nestjs_architecture',
      tags: [
        'dependency_injection',
        'module_architecture',
        'provider_lifecycle',
        'request_lifecycle',
        'guards_pipes_interceptors',
        'middleware_pipeline',
        'exception_handling',
        'circular_dependency',
        'configuration',
      ],
    },
    {
      group: 'express_node',
      tags: ['middleware_pipeline', 'routing', 'error_handling'],
    },
    {
      group: 'performance_reliability',
      tags: [
        'caching',
        'batching',
        'concurrency',
        'backpressure',
        'timeouts_retries',
        'observability',
        'graceful_shutdown',
      ],
    },
    {
      group: 'devops_runtime',
      tags: [
        'containerization',
        'dockerfile',
        'image_layers',
        'volumes',
        'container_networking',
        'compose',
        'environment_config',
        'secrets_management',
        'healthchecks',
        'ci_cd',
        'deployment',
        'cloud_architecture',
        'cloud_security',
        'cloud_networking',
        'serverless_architecture',
        'infrastructure_as_code',
        'scalability',
        'cost_optimization',
        'incident_response',
      ],
    },
    {
      group: 'architecture_async',
      tags: [
        'event_driven_architecture',
        'microservices_architecture',
        'messaging',
        'eventual_consistency',
        'outbox_pattern',
      ],
    },
  ],
};
